# Generated by Django 6.0.5 on 2026-05-26 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_split_leave_category_and_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='core.leavecategory'),
        ),
    ]
