# Generated by Django 6.0.5 on 2026-06-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_system_roles_workflows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr', 'HR Manager'), ('finance', 'Finance Manager'), ('marketing', 'Marketing Manager'), ('staff', 'Branch Staff'), ('backoffice', 'Back Office Staff'), ('branch', 'Branch Manager'), ('branch_accountant', 'Branch Accountant'), ('followup', 'Follow Up Staff')], max_length=20),
        ),
    ]
