# Generated by Django 6.0.5 on 2026-06-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_default_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcase',
            name='status',
            field=models.CharField(choices=[('opened', 'Case opened'), ('documents_verified', 'Documents verified'), ('application_created', 'Application created'), ('applied_universities', 'File submitted'), ('portals_uploaded', 'Submitted online'), ('tracking_responses', 'Tracking response'), ('customer_updated', 'Customer status updated'), ('completed', 'Case completed')], default='opened', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientcase',
            name='universities_applied',
            field=models.TextField(blank=True, help_text='Authorities or providers submitted to (one per line).'),
        ),
        migrations.AlterField(
            model_name='clientcase',
            name='university_response_summary',
            field=models.TextField(blank=True, help_text='Response or outcome from authority or provider.'),
        ),
    ]
