# Generated by Django 6.0.5 on 2026-06-09 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_clientcase_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMemberDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_card', models.FileField(blank=True, null=True, upload_to='team_docs/%Y/%m/aadhaar/')),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='team_docs/%Y/%m/offer/')),
                ('passport_image', models.FileField(blank=True, null=True, upload_to='team_docs/%Y/%m/passport/')),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('emirates_id_image', models.FileField(blank=True, null=True, upload_to='team_docs/%Y/%m/emirates_id/')),
                ('emirates_id_expiry', models.DateField(blank=True, null=True)),
                ('insurance_image', models.FileField(blank=True, null=True, upload_to='team_docs/%Y/%m/insurance/')),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('labour_card_image', models.FileField(blank=True, null=True, upload_to='team_docs/%Y/%m/labour_card/')),
                ('labour_card_expiry', models.DateField(blank=True, null=True)),
                ('labour_contract_image', models.FileField(blank=True, null=True, upload_to='team_docs/%Y/%m/labour_contract/')),
                ('labour_contract_expiry', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team member documents',
                'verbose_name_plural': 'Team member documents',
            },
        ),
    ]
