# Generated by Django 6.0.5 on 2026-06-09 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_lead_services(apps, schema_editor):
    LeadService = apps.get_model("core", "LeadService")
    LeadServiceDocumentType = apps.get_model("core", "LeadServiceDocumentType")

    visa, _ = LeadService.objects.get_or_create(
        code="visa-processing",
        defaults={
            "name": "Visa Processing",
            "description": "New visa and renewal applications",
            "sort_order": 1,
            "is_active": True,
        },
    )
    pro, _ = LeadService.objects.get_or_create(
        code="pro-services",
        defaults={
            "name": "PRO Services",
            "description": "Government and PRO-related work",
            "sort_order": 2,
            "is_active": True,
        },
    )

    visa_docs = [
        ("passport", "Passport copy", "Clear scan of passport bio page", True, 1),
        ("photo", "Passport photo", "White background, recent photo", True, 2),
        ("offer-letter", "Offer letter", "Signed offer or employment letter", False, 3),
    ]
    for code, name, help_text, required, order in visa_docs:
        LeadServiceDocumentType.objects.get_or_create(
            service=visa,
            code=code,
            defaults={
                "name": name,
                "help_text": help_text,
                "is_required": required,
                "sort_order": order,
                "is_active": True,
            },
        )

    pro_docs = [
        ("trade-license", "Trade license copy", "Valid trade license", True, 1),
        ("emirates-id", "Emirates ID copy", "Front and back if applicable", True, 2),
        ("moa", "MOA / Agreement", "Memorandum of association if required", False, 3),
    ]
    for code, name, help_text, required, order in pro_docs:
        LeadServiceDocumentType.objects.get_or_create(
            service=pro,
            code=code,
            defaults={
                "name": name,
                "help_text": help_text,
                "is_required": required,
                "sort_order": order,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_teammemberdocuments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead service',
                'verbose_name_plural': 'Lead services',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='core.leadservice'),
        ),
        migrations.CreateModel(
            name='LeadServiceDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.SlugField(blank=True)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_types', to='core.leadservice')),
            ],
            options={
                'verbose_name': 'Lead service document type',
                'verbose_name_plural': 'Lead service document types',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LeadServiceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='leads/service_docs/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_documents', to='core.lead')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_service_documents_uploaded', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploads', to='core.leadservicedocumenttype')),
            ],
            options={
                'ordering': ['document_type__sort_order', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='leadservicedocumenttype',
            constraint=models.UniqueConstraint(fields=('service', 'code'), name='uniq_lead_service_doc_type_code'),
        ),
        migrations.AddConstraint(
            model_name='leadservicedocument',
            constraint=models.UniqueConstraint(fields=('lead', 'document_type'), name='uniq_lead_service_document_type'),
        ),
        migrations.RunPython(seed_lead_services, migrations.RunPython.noop),
    ]
