# Generated by Django 6.0.5 on 2026-06-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_seed_lead_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='service_documents_zip',
            field=models.FileField(blank=True, upload_to='leads/service_zips/%Y/%m/', verbose_name='Service documents (ZIP)'),
        ),
    ]
