# Generated by Django 6.0.5 on 2026-06-11 03:52

import django.db.models.deletion
from django.db import migrations, models


def mark_converted_sends_to_followup(apps, schema_editor):
    LeadStatus = apps.get_model("core", "LeadStatus")
    LeadStatus.objects.filter(code="converted").update(sends_to_followup=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_lead_client_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='sent_to_followup_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadstatus',
            name='sends_to_followup',
            field=models.BooleanField(default=False, help_text='When staff sets this status, the lead is sent to the follow-up team.'),
        ),
        migrations.CreateModel(
            name='LeadExtractedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='leads/extracted/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_documents', to='core.lead')),
            ],
            options={
                'ordering': ['original_name', 'created_at'],
            },
        ),
        migrations.RunPython(mark_converted_sends_to_followup, migrations.RunPython.noop),
    ]
