# Generated by Django 6.0.5 on 2026-06-11 04:29

from django.db import migrations, models


def seed_approved_status(apps, schema_editor):
    LeadStatus = apps.get_model("core", "LeadStatus")
    LeadStatus.objects.get_or_create(
        code="approved",
        defaults={
            "name": "Approved",
            "badge_style": "won",
            "sort_order": 5,
            "is_active": True,
            "sends_to_backoffice": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_lead_followup_handoff_extracted_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='sent_to_backoffice_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadstatus',
            name='sends_to_backoffice',
            field=models.BooleanField(default=False, help_text='When follow-up sets this status, the lead is sent to back office for processing.'),
        ),
        migrations.RunPython(seed_approved_status, migrations.RunPython.noop),
    ]
