# Generated by Django 6.0.5 on 2026-06-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_lead_backoffice_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='service_zip_verified',
            field=models.BooleanField(default=False, help_text='Follow-up confirmed staff ZIP when no extracted files are available.'),
        ),
        migrations.AddField(
            model_name='leadextracteddocument',
            name='followup_checked',
            field=models.BooleanField(default=False),
        ),
    ]
