# Generated by Django 6.0.5 on 2026-06-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_lead_lost_reason_and_status_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='payment_screenshot',
            field=models.ImageField(blank=True, upload_to='leads/payment_screenshots/%Y/%m/', verbose_name='Payment screenshot'),
        ),
        migrations.AddField(
            model_name='lead',
            name='payment_verified',
            field=models.BooleanField(default=False, help_text='Staff confirmed customer payment before converting the lead.'),
        ),
    ]
