# Generated by Django 6.0.5 on 2026-06-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_lead_service_procedures'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='service_expire_date',
            field=models.DateField(blank=True, help_text='Service expiry date set by follow-up; shown on portal calendars.', null=True),
        ),
    ]
