# Generated by Django 6.0.6 on 2026-06-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_lead_service_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadprocedurestep',
            name='backoffice_document',
            field=models.FileField(blank=True, upload_to='leads/procedure_docs/backoffice/%Y/%m/'),
        ),
    ]
