# Generated by Django 6.0.6 on 2026-06-25 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_lead_renewal_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='renewal_handled',
            field=models.BooleanField(default=False, help_text='Indicates if this renewal alert has been handled (e.g. by creating a new lead).'),
        ),
        migrations.AddField(
            model_name='lead',
            name='renewed_from',
            field=models.ForeignKey(blank=True, help_text='If this lead was created as a renewal, this links to the original lead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_leads', to='core.lead'),
        ),
    ]
