# Generated by Django 6.0.5 on 2026-06-09 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0005_branchmanager_is_active'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_members', to='branch.branch'),
        ),
    ]
