# Generated by Django 6.0.5 on 2026-06-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staff_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='staff',
            name='other_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='staff',
            name='total_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
