# Generated by Django 6.0.5 on 2026-06-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_backoffice_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='backoffice',
            name='is_backoffice_head',
            field=models.BooleanField(default=False, help_text='Head can approve/reject leads and see all back office team data.'),
        ),
    ]
