# Generated by Django 6.0.5 on 2026-05-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_hr_model_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hr',
            options={'verbose_name': 'HR profile', 'verbose_name_plural': 'HR profiles'},
        ),
        migrations.AlterField(
            model_name='hr',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
