"""Sample data for dashboard demos until real modules are wired."""


def _lead(**kwargs):
    status = kwargs["status"]
    badge = {
        "New": "new",
        "Contacted": "active",
        "Qualified": "pending",
        "Converted": "won",
        "Lost": "closed",
    }[status]
    return {**kwargs, "badge": badge}


SAMPLE_LEADS = [
    _lead(
        id="L-001",
        name="Rajesh Sharma",
        company="Tech Corp Ltd",
        phone="+91 98001 22334",
        email="rajesh@techcorp.in",
        source="Website",
        status="New",
        assigned="Suresh B.",
        followup="30 Jun 2026",
        initials="RS",
    ),
    _lead(
        id="L-002",
        name="Priya Nair",
        company="Infosys Ltd",
        phone="+91 99001 33445",
        email="priya@infosys.com",
        source="Referral",
        status="Contacted",
        assigned="Kavitha M.",
        followup="01 Jul 2026",
        initials="PN",
    ),
    _lead(
        id="L-003",
        name="Vikram Anand",
        company="HCL Tech",
        phone="+91 97001 44556",
        email="vikram@hcl.com",
        source="LinkedIn",
        status="Qualified",
        assigned="Deepak P.",
        followup="28 Jun 2026",
        initials="VA",
    ),
    _lead(
        id="L-004",
        name="Sunita Rao",
        company="Wipro Ltd",
        phone="+91 96001 55667",
        email="sunita@wipro.com",
        source="Cold Call",
        status="Converted",
        assigned="Suresh B.",
        followup="29 Jun 2026",
        initials="SR",
    ),
    _lead(
        id="L-005",
        name="Arun Kumar",
        company="TCS Ltd",
        phone="+91 95001 66778",
        email="arun@tcs.com",
        source="Google Ads",
        status="New",
        assigned="Kavitha M.",
        followup="02 Jul 2026",
        initials="AK",
    ),
    _lead(
        id="L-006",
        name="Meena Pillai",
        company="Cognizant",
        phone="+91 94001 77889",
        email="meena@cognizant.com",
        source="Trade Show",
        status="Contacted",
        assigned="Deepak P.",
        followup="03 Jul 2026",
        initials="MP",
    ),
    _lead(
        id="L-007",
        name="Karthik Velu",
        company="Zoho Corp",
        phone="+91 93001 88990",
        email="karthik@zoho.com",
        source="Referral",
        status="Lost",
        assigned="Suresh B.",
        followup="25 Jun 2026",
        initials="KV",
    ),
    _lead(
        id="L-008",
        name="Lakshmi Devi",
        company="Freshworks",
        phone="+91 92001 99001",
        email="lakshmi@freshworks.com",
        source="Website",
        status="Qualified",
        assigned="Kavitha M.",
        followup="04 Jul 2026",
        initials="LD",
    ),
]
