# Generated by Django 6.0.5 on 2026-05-26 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_branchmanager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['-created_at']},
        ),
    ]
