# Generated by Django 6.0.5 on 2026-06-17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch", "0005_branchmanager_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BranchMonthlyTarget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period_month", models.PositiveSmallIntegerField()),
                ("period_year", models.PositiveSmallIntegerField()),
                ("target_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="branch_targets_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_targets",
                        to="branch.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branch monthly target",
                "verbose_name_plural": "Branch monthly targets",
                "ordering": ["-period_year", "-period_month"],
                "unique_together": {("branch", "period_month", "period_year")},
            },
        ),
    ]
